# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: georoutedmsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='georoutedmsg.proto',
  package='georoutedmsg',
  syntax='proto3',
  serialized_options=b'Z%./proto-gen/georoutedmsg;georoutedmsg',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12georoutedmsg.proto\x12\x0cgeoroutedmsg\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x08Position\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"t\n\x0cGeoRoutedMsg\x12\x10\n\x08msgBytes\x18\x01 \x01(\x0c\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x08position\x18\x03 \x01(\x0b\x32\x16.georoutedmsg.PositionB\'Z%./proto-gen/georoutedmsg;georoutedmsgb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='georoutedmsg.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='georoutedmsg.Position.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='georoutedmsg.Position.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=116,
)


_GEOROUTEDMSG = _descriptor.Descriptor(
  name='GeoRoutedMsg',
  full_name='georoutedmsg.GeoRoutedMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgBytes', full_name='georoutedmsg.GeoRoutedMsg.msgBytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='georoutedmsg.GeoRoutedMsg.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='georoutedmsg.GeoRoutedMsg.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=234,
)

_GEOROUTEDMSG.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GEOROUTEDMSG.fields_by_name['position'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['GeoRoutedMsg'] = _GEOROUTEDMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'georoutedmsg_pb2'
  # @@protoc_insertion_point(class_scope:georoutedmsg.Position)
  })
_sym_db.RegisterMessage(Position)

GeoRoutedMsg = _reflection.GeneratedProtocolMessageType('GeoRoutedMsg', (_message.Message,), {
  'DESCRIPTOR' : _GEOROUTEDMSG,
  '__module__' : 'georoutedmsg_pb2'
  # @@protoc_insertion_point(class_scope:georoutedmsg.GeoRoutedMsg)
  })
_sym_db.RegisterMessage(GeoRoutedMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
